version: '3'

services:
  db:
    image: mysql
    environment:
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: task_manager
      MYSQL_ROOT_PASSWORD: toor
  dev:
    build: .
    volumes:
      - .:/source
    ports:
      - "1337:1337"
    depends_on:
      - db
    environment:
      - NODE_ENV=development PORT=1337
  web:
    build: .
    volumes:
      - .:/source
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - NODE_ENV=production PORT=8080
